In [ ]:
#1
class Student:
    def __init__(self, name='Just a student', dept='nothing'):
        self.__name = name
        self.__department = dept
    def set_department(self, dept):
        self.__department = dept
    def get_name(self):
        return self.__name
    def set_name(self,name):
        self.__name = name
    def __str__(self):
        return 'Name: '+self.__name+' Department: '+self.__department


#write your code here
class BBA_Student(Student):
  def __init__(self,name = "default"):
    super().__init__(name,"BBA")


print(BBA_Student())
print(BBA_Student('Humpty Dumpty'))
print(BBA_Student('Little Bo Peep'))

Name: default Department: BBA
Name: Humpty Dumpty Department: BBA
Name: Little Bo Peep Department: BBA

In [ ]:
#Class BAAL
class Student:
  count = 0
  def __init__(self,name,dept,cg=0):
    Student.count += 1
    self.name = name
    self.dept = dept
    self.cg = cg
    self.count = Student.count
  @classmethod
  def CreateStudent(cls):
    return cls(name="Unknown",dept="CSE")
  def updateCGPA(self,cg):
    self.cg = cg
  def details(self):
    if self.name == "Unknown":
      print(f"Student{self.count} Created with default parameters\n*********************************")
    print(f"Student{self.count}\nName: {self.name}\nDepartment: {self.dept}\nCGPA: {self.cg}\n*********************************")
  @classmethod
  def compare(cls,x,y):
    if x > y:
      print(f"{x}>{y}") 
    else: 
      print(f"{y}>{x}")

Student1 = Student.CreateStudent()
Student2 = Student("Karim","EEE")
Student3 = Student("Rahim","ECE")
Student1.details()
Student2.updateCGPA(3.33)
Student3.updateCGPA(3.1)

Student4=Student("Sani","BBA",3.53)

Student2.details()
Student3.details()
Student.compare(3.22,3.50)

Student1 Created with default parameters
*********************************
Student1
Name: Unknown
Department: CSE
CGPA: 0
*********************************
Student2
Name: Karim
Department: EEE
CGPA: 3.33
*********************************
Student3
Name: Rahim
Department: ECE
CGPA: 3.1
*********************************
3.5>3.22

In [ ]:
#2
class Vehicle:
    def __init__(self):
        self.x = 0
        self.y = 0
    def moveUp(self):
        self.y+=1
    def moveDown(self):
        self.y-=1
    def moveRight(self):
        self.x+=1
    def moveLeft(self):
        self.x-=1
    def __str__(self):
        return '('+str(self.x)+' , '+str(self.y)+')'
#write your code here
class Vehicle2010(Vehicle):
  def __init__(self):
    super().__init__()
  def moveUpperRight(self):
    self.moveUp()
    self.moveRight()
  def moveUpperLeft(self):
    self.moveUp()
    self.moveLeft()
  def moveLowerRight(self):
    self.moveDown()
    self.moveRight()
  def moveLowerLeft(self):
    self.moveDown()
    self.moveLeft()
  def equals(self,other):
    if self.x == other.x and self.y == other.y:
      return True
    else:
      return False


print('Part 1')
print('------')
car = Vehicle()
print(car)
car.moveUp()
print(car)
car.moveLeft()
print(car)
car.moveDown()
print(car)
car.moveRight()
print(car)
print('------')
print('Part 2')
print('------')
car1 = Vehicle2010()
print(car1)
car1.moveLowerLeft()
print(car1)
car2 = Vehicle2010()
car2.moveLeft()
print(car1.equals(car2))
car2.moveDown()
print(car1.equals(car2))

Part 1
------
(0 , 0)
(0 , 1)
(-1 , 1)
(-1 , 0)
(0 , 0)
------
Part 2
------
(0 , 0)
(-1 , -1)
False
True

In [ ]:
#3
class Tournament:
    def __init__(self,name='Default'):
        self.__name = name
    def set_name(self,name):
        self.__name = name
    def get_name(self):
        return self.__name

#write your code here
class Cricket_Tournament(Tournament):
  def __init__(self,name='Default',num = 0, types = "No type"):
    super().__init__(name)
    self.num = num
    self.types = types
  def detail(self):
    return f"Cricket Tournament Name: {self.get_name()}\nNumber of Teams: {self.num}\nType: {self.types}"
class Tennis_Tournament(Tournament):
  def __init__(self,name,num):
    super().__init__(name)
    self.num = num
  def detail(self):
    return f"Tennis Tournament Name: {self.get_name()}\nNumber of Players: {self.num}"

ct1 = Cricket_Tournament()
print(ct1.detail())
print("-----------------------")
ct2 = Cricket_Tournament("IPL",10,"t20")
print(ct2.detail())
print("-----------------------")
tt = Tennis_Tournament("Roland Garros",128)
print(tt.detail())

Cricket Tournament Name: Default
Number of Teams: 0
Type: No type
-----------------------
Cricket Tournament Name: IPL
Number of Teams: 10
Type: t20
-----------------------
Tennis Tournament Name: Roland Garros
Number of Players: 128

In [ ]:
#4
class Product:
    def __init__(self,id, title, price):
        self.__id = id
        self.__title = title
        self.__price = price
    def get_id_title_price(self):
        return "ID: "+str(self.__id)+" Title:"+self.__title+ " Price: "+str(self.__price)
#write your code here
class Book(Product):
  def __init__(self,id,title,price,isbn,publisher):
    super().__init__(id,title,price)
    self.isbn = isbn
    self.publisher = publisher
  def printDetail(self):
    return f"{self.get_id_title_price()}\nISBN: {self.isbn} Publisher: {self.publisher}"
class CD(Product):
  def __init__(self,id,title,price,band,time,genre):
    super().__init__(id,title,price)
    self.band = band
    self.time = time
    self.genre = genre
  def printDetail(self):
    return f"{self.get_id_title_price()}\nBand: {self.band} Duration: {self.time} minutes\nGenre: {self.genre}"
book = Book(1,"The Alchemist",500,"97806","HarperCollins")
print(book.printDetail())
print("-----------------------")
cd = CD(2,"Shotto",300,"Warfaze",50,"Hard Rock")
print(cd.printDetail())

ID: 1 Title:The Alchemist Price: 500
ISBN: 97806 Publisher: HarperCollins
-----------------------
ID: 2 Title:Shotto Price: 300
Band: Warfaze Duration: 50 minutes
Genre: Hard Rock

In [ ]:
#5
class Animal:   
    def __init__(self,sound):
        self.__sound = sound
        
    def makeSound(self):
        return self.__sound
        


class Printer:   
    def printSound(self, a):
        print(a.makeSound())


#write your code here
class Dog(Animal,Printer):
  def __init__(self,sound):
    super().__init__(sound)
class Cat(Animal,Printer):
  def __init__(self,sound):
    super().__init__(sound)
d1 = Dog('bark')
c1 = Cat('meow')
a1 = Animal('Animal does not make sound')
pr = Printer()
pr.printSound(a1)
pr.printSound(c1)
pr.printSound(d1)

Animal does not make sound
meow
bark

In [ ]:
#6
class Shape:

  def __init__(self, name='Default', height=0, base=0):
    self.area = 0
    self.name = name
    self.height = height
    self.base = base

  def get_height_base(self):
    return "Height: "+str(self.height)+",Base: "+str(self.base)

#write your code here
class triangle(Shape):
  def __init__(self,name='Default', height=0, base=0):
    super().__init__(name,height,base)
  def calcArea(self):
    self.area = (self.height * self.base)/2
  def printDetail(self):
    return f"Shape name: {self.name}\n{self.get_height_base()}\n{self.area}"
class trapezoid(Shape):
  def __init__(self,name, height, base,side):
    super().__init__(name,height,base)
    self.side = side
  def calcArea(self):
    self.area = ((self.side+self.base)/2)*self.height
  def printDetail(self):
    return f"Shape name: {self.name}\n{self.get_height_base()}, Side_A: {self.side}\n{self.area}"
tri_default = triangle()
tri_default.calcArea()
print(tri_default.printDetail())
print('--------------------------')
tri = triangle('Triangle', 10, 5)
tri.calcArea()
print(tri.printDetail())
print('---------------------------')
trap = trapezoid('Trapezoid', 10, 6, 4)
trap.calcArea()
print(trap.printDetail())

Shape name: Default
Height: 0,Base: 0
0.0
--------------------------
Shape name: Triangle
Height: 10,Base: 5
25.0
---------------------------
Shape name: Trapezoid
Height: 10,Base: 6, Side_A: 4
50.0

In [32]:
#7
class Football:

  def __init__(self, team_name, name, role):
    self.__team = team_name
    self.__name = name
    self.role = role
    self.earning_per_match = 0

  def get_name_team(self):
    return 'Name: '+self.__name+', Team Name: ' +self.__team

#write your code here
class Player(Football):
  def __init__(self,team,name,role,goal,match):
    super().__init__(team,name,role)
    self.goal = goal
    self.match = match
    self.earning_per_match = (self.goal * 1000) + (self.match * 10)
  def calculate_ratio(self):
    self.ratio = self.goal/self.match
  def print_details(self):
    print(f"{self.get_name_team()}\nTeam Role: {self.role}\nTotal Goal: {self.goal}, Total Played: {self.match}")
    print(f"Goal Ratio: {self.ratio}\nMatch Earning: {self.earning_per_match}")
class Manager(Football):
  def __init__(self,team,name,role,win):
    super().__init__(team,name,role)
    self.win = win
    self.earning_per_match = self.win * 1000
  def print_details(self):
    print(f"{self.get_name_team()}\nTeam Role: {self.role}\nTotal Win: {self.win}\nMatch Earning: {self.earning_per_match}")
player_one = Player('Juventus', 'Ronaldo', 'Striker', 25, 32)
player_one.calculate_ratio()
player_one.print_details()
print('------------------------------------------')
manager_one = Manager('Real Madrid', 'Zidane', 'Manager', 25)
manager_one.print_details()

Name: Ronaldo, Team Name: Juventus
Team Role: Striker
Total Goal: 25, Total Played: 32
Goal Ratio: 0.78125
Match Earning: 25320
------------------------------------------
Name: Zidane, Team Name: Real Madrid
Team Role: Manager
Total Win: 25
Match Earning: 25000