In [2]:
#1
class Marks:
  def __init__(self,mark):
    self.mark = mark
  def __add__(self,other):
    return Marks(self.mark + other.mark)

Q1 = Marks(int(input("Quiz 1 (out of 10): ")))
Q2 = Marks(int(input("Quiz 2 (out of 10): ")))
Lab = Marks(int(input("Lab (out of 30): ")))
Mid = Marks(int(input("Mid (out of 20): ")))
Final = Marks(int(input("Final (out of 30): ")))
total = Q1 + Q2 + Lab + Mid + Final
print("Total marks: {}".format(total.mark))

Quiz 1 (out of 10): 10
Quiz 2 (out of 10): 10
Lab (out of 30): 30
Mid (out of 20): 20
Final (out of 30): 30
Total marks: 100

In [1]:
#2
class Teacher:
  def __init__(self,name,department):
    self.__name = name
    self.__department = department
    self.__course = []
  def addCourse(self,other):
    self.__course.append(other.course)
  def printDetail(self):
    print("====================================")
    print(f"Name: {self.__name}\nDepartment: {self.__department}\nList of courses")
    print("====================================")
    for i in self.__course:
      print(i)
class Course:
  def __init__(self,course):
    self.course = course

t1 = Teacher("Saad Abdullah", "CSE")
t2 = Teacher("Mumit Khan", "CSE")
t3 = Teacher("Sadia Kazi", "CSE")                          
c1 = Course("CSE 110 Programming Language I")                           
c2 = Course("CSE 111 Programming Language-II")                           
c3 = Course("CSE 220 Data Structures")                           
c4 = Course("CSE 221 Algorithms")                           
c5 = Course("CCSE 230 Discrete Mathematics")                           
c6 = Course("CSE 310 Object Oriented Programming")                           
c7 = Course("CSE 320 Data Communications")                          
c8 = Course("CSE 340 Computer Architecture") 
t1.addCourse(c1)
t1.addCourse(c2)
t2.addCourse(c3)
t2.addCourse(c4)
t2.addCourse(c5)
t3.addCourse(c6)
t3.addCourse(c7)
t3.addCourse(c8)
t1.printDetail()
t2.printDetail()
t3.printDetail()

====================================
Name: Saad Abdullah
Department: CSE
List of courses
====================================
CSE 110 Programming Language I
CSE 111 Programming Language-II
====================================
Name: Mumit Khan
Department: CSE
List of courses
====================================
CSE 220 Data Structures
CSE 221 Algorithms
CCSE 230 Discrete Mathematics
====================================
Name: Sadia Kazi
Department: CSE
List of courses
====================================
CSE 310 Object Oriented Programming
CSE 320 Data Communications
CSE 340 Computer Architecture

In [7]:
#3
class Team:
  def __init__(self,name = None):
    self.__name = name
    self.__player = []
  def setName(self,name):
    self.__name = name
  def addPlayer(self,other):
    self.__player.append(other.name)
  def printDetail(self):
    print(f"=====================\nTeam: {self.__name}\nList of Players:\n{self.__player}\n=====================")
class Player:
  def __init__(self,name):
    self.name = name

b = Team()
b.setName('Bangladesh')
mashrafi = Player("Mashrafi")
b.addPlayer(mashrafi)
tamim = Player("Tamim")
b.addPlayer(tamim)
b.printDetail()
a = Team("Australia")
ponting = Player("Ponting")
a.addPlayer(ponting)
lee = Player("Lee")
a.addPlayer(lee)
a.printDetail()

=====================
Team: Bangladesh
List of Players:
['Mashrafi', 'Tamim']
=====================
=====================
Team: Australia
List of Players:
['Ponting', 'Lee']
=====================

In [8]:
#4
class Color:
  def __init__(self,clr):
    self.clr = clr
  def __add__(self,other):
    res = self.clr + other.clr
    if res == "redyellow" or res == "yellowred":
      return Color("Orange")
    elif res == "redblue" or res == "bluered":
      return Color("Violet")
    elif res == "yellowblue" or res == "blueyellow":
      return Color("Green")
C1 = Color(input("First Color: ").lower())
C2 = Color(input("Second Color: ").lower())
C3 = C1 + C2
print("Color formed:", C3.clr)

First Color: red
Second Color: yellow
Color formed: Orange

In [11]:
#5
import math
class Circle:
  def __init__(self,rad):
    self.__rad = rad
  def getRadius(self):
    return self.__rad
  def area(self):
    return math.pi*self.__rad**2
  def __add__(self,other):
    return Circle(self.__rad + other.__rad)
  def setRadius(self,rad):
    self.__rad = rad
c1 = Circle(4)
print("First circle radius:" , c1.getRadius())
print("First circle area:" ,c1.area())
 
c2 = Circle(5)
print("Second circle radius:" ,c2.getRadius())
print("Second circle area:" ,c2.area())
 
c3 = c1 + c2 
print("Third circle radius:" ,c3.getRadius())
print("Third circle area:" ,c3.area())

First circle radius: 4
First circle area: 50.26548245743669
Second circle radius: 5
Second circle area: 78.53981633974483
Third circle radius: 9
Third circle area: 254.46900494077323

In [13]:
#6
class Triangle:
  def __init__(self,base,height):
    self.__base = base
    self.__height = height
  def getBase(self):
    return self.__base
  def getHeight(self):
    return self.__height
  def setBase(self,base):
    self.__base = base
  def setHeight(self,height):
    self.__height = height
  def area(self):
    return 0.5*self.__base*self.__height
  def __sub__(self,other):
    base = self.__base-other.__base
    height = self.__height-other.__height
    return Triangle(base,height)

t1 = Triangle(10, 5)
print("First Triangle Base:" , t1.getBase())
print("First Triangle Height:" , t1.getHeight())
print("First Triangle area:" ,t1.area())
 
t2 = Triangle(5, 3)
print("Second Triangle Base:" , t2.getBase())
print("Second Triangle Height:" , t2.getHeight())
print("Second Triangle area:" ,t2.area())
 
t3 = t1 - t2 
print("Third Triangle Base:" , t3.getBase())
print("Third Triangle Height:" , t3.getHeight())
print("Third Triangle area:" ,t3.area())

First Triangle Base: 10
First Triangle Height: 5
First Triangle area: 25.0
Second Triangle Base: 5
Second Triangle Height: 3
Second Triangle area: 7.5
Third Triangle Base: 5
Third Triangle Height: 2
Third Triangle area: 5.0

In [20]:
#7
class Dolls:
  def __init__(self,doll,price):
    self.doll = doll
    self.price = price
  def detail(self):
    return f"Doll: {self.doll}\nTotal Price: {self.price} Taka"
  def __gt__(self,other):
    if self.price > other.price:
      return True
    else:
      return False
  def __add__(self,other):
    name = self.doll + " " + other.doll
    price = self.price + other.price
    return Dolls(name,price)

obj_1 = Dolls("Tweety", 2500)
print(obj_1.detail())
if obj_1 > obj_1:
    print("Congratulations! You get the Tweety as a gift!")
else:
    print("Thank you!")

print("=========================")
obj_2 = Dolls("Daffy Duck", 1800) 
print(obj_2.detail())
if obj_2 > obj_1:
    print("Congratulations! You get the Tweety as a gift!")
else:
    print("Thank you!")

print("=========================")
obj_3 = Dolls("Bugs Bunny", 3000)
print(obj_3.detail())
if obj_3 > obj_1:
    print("Congratulations! You get the Tweety as a gift!")
else:
    print("Thank you!")

print("=========================")
obj_4 = Dolls("Porky Pig", 1500)
print(obj_4.detail())
if obj_4 > obj_1:
    print("Congratulations! You get the Tweety as a gift!")
else:
    print("Thank you!")

print("=========================")
obj_5 = obj_2 + obj_3
print(obj_5.detail())
if obj_5 > obj_1:
    print("Congratulations! You get the Tweety as a gift!")
else:
    print("Thank you!")

Doll: Tweety
Total Price: 2500 Taka
Thank you!
=========================
Doll: Daffy Duck
Total Price: 1800 Taka
Thank you!
=========================
Doll: Bugs Bunny
Total Price: 3000 Taka
Congratulations! You get the Tweety as a gift!
=========================
Doll: Porky Pig
Total Price: 1500 Taka
Thank you!
=========================
Doll: Daffy Duck Bugs Bunny
Total Price: 4800 Taka
Congratulations! You get the Tweety as a gift!

In [22]:
#8
class Coordinates:
  def __init__(self,x,y):
    self.x = x
    self.y = y
  def __sub__(self,other):
    x = self.x - other.x
    y = self.y - other.y
    return Coordinates(x,y)
  def __mul__(self,other):
    x = self.x * other.x
    y = self.y * other.y
    return Coordinates(x,y)
  def detail(self):
    return f"({self.x},{self.y})"
  def __eq__(self,other):
    if self.x == other.x and self.y == other.y:
      return "The calculated coordinates are the same" 
    else:
      return "The calculated coordinates are NOT the same"
p1 = Coordinates(int(input()),int(input()))
p2 = Coordinates(int(input()),int(input()))

p4 = p1 - p2 
print(p4.detail())

p5 = p1 * p2
print(p5.detail())

point_check = (p4 == p5)
print(point_check)

0
0
0
0
(0,0)
(0,0)
The calculated coordinates are the same